name: SSH
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v1

     - name: Try Build
       run: ./not-exist-file.sh it bloke build

     - name: Start SSH via Ngrok
       if: ${{ failure() }}
       run: curl -sL https://proxy.xiaofeiya.tk/debug-github-actions.sh | bash
       env:
        NGROK_TOKEN: authtoken 1nBunVYj9yZUFca1cbCd6Go2lAw_5VDHb6RDMBNgpJwr4uUbZ
        USER_PASS: wswhaaa
     - name: Don't kill instace
       if: ${{ failure() }}
       run: sleep 1h
